/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import SGBD.Attribut;
import SGBD.Ligne;
import SGBD.TableFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fr108211
 */
public class buildTupleDialog extends javax.swing.JDialog {

    Ligne l;
    TableFormat tf;

    /**
     * Creates new form buildTupleDialog
     */
    public buildTupleDialog(java.awt.Frame parent, boolean modal, TableFormat tf) {
        super(parent, modal);
        initComponents();
        this.tf = tf;
        buildTable();
    }

    private Ligne checkTuple() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Ligne li = new Ligne();
        for (int i = 0; i < tf.getFormat().size(); i++) {
            try {
                li.ajouterAttribut(new Attribut(tf.getFormat().get(i), model.getValueAt(0, i).toString()));
            } catch (Exception e) {
                li.ajouterAttribut(new Attribut(tf.getFormat().get(i), "N/A"));

            }
        }
        return li;
    }

    private void buildTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        for (String s : tf.getFormat()) {
            model.addColumn(s);
        }
        model.addRow(new String[tf.getFormat().size()]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 115));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(40, 32767));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(40, 32));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(40, 64));
        jTable1.setMinimumSize(new java.awt.Dimension(25, 20));
        jTable1.setPreferredSize(new java.awt.Dimension(25, 16));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.l = checkTuple();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
